services:
  api:
    build:
      context: ./app
    ports:
      - "8088:8000"
    environment:
      - APP_NAME=TrickyTunnels
      - APP_ENV=production
      - JWT_SECRET=dev-jwt-secret-should-not-leak
      - INTERNAL_ADMIN_URL=http://admin-internal:9000
      - FLAG=APIverse{tricky_tunnels_info_disclosure}
      - DATA_DIR=/data
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data: